# Generated by Django 6.1 on 2026-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(default='d6503a62afc14d2aac2a0841e30d4d23', editable=False, max_length=40, unique=True),
        ),
    ]
