# Generated by Django 6.1 on 2026-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(default='58cb8ed5605a474dbf37a12464376f7d', editable=False, max_length=40, unique=True),
        ),
    ]
