# Generated by Django 6.1 on 2026-08-29 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text="True if Razorpay wasn't configured and this payment was simulated instead."),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True),
        ),
    ]
