# Generated by Django 6.1 on 2026-08-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_reference_id'),
        ('payments', '0003_payment_is_simulated_payment_razorpay_order_id_and_more'),
    ]

    operations = [
    ]
