# Generated by Django 6.1 on 2026-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_reference_id_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(help_text="e.g., 'earning', 'withdrawal', 'commission'", max_length=50),
        ),
    ]
