# Generated by Django 6.1 on 2026-09-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bulkservicerequest_status'),
        ('payments', '0006_remove_wallettransaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bulk_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.bulkservicerequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
    ]
