# Generated by Django 5.2.17 on 2026-09-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('workers', '0006_federationpricing_category_overrides_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.governmentopportunity')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gov_applications', to='workers.workerprofile')),
            ],
            options={
                'unique_together': {('opportunity', 'worker')},
            },
        ),
    ]
