# Generated by Django 5.2.17 on 2026-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_governmentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentopportunity',
            name='google_form_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
