# Generated by Django 5.2.17 on 2026-09-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
    ]
