# Generated by Django 5.2.17 on 2026-09-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_communitymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychannel',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='community.community'),
        ),
    ]
