# Generated by Django 5.2.17 on 2026-09-05
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_tour',
            field=models.BooleanField(default=False),
        ),
    ]
