# Generated by Django 6.1 on 2026-08-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='tool', help_text='SVG icon key used by the front-end icon set.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('fixed_visit_charge', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('description', models.TextField(blank=True)),
                ('required_skill', models.CharField(blank=True, max_length=100)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('tools_required', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('emergency', 'Emergency'), ('residential', 'Residential'), ('institutional', 'Institutional'), ('builder', 'Builder / Project')], default='standard', max_length=20)),
                ('fixed_labour_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_days', models.PositiveIntegerField(default=7)),
                ('cancellation_policy', models.TextField(blank=True, default='Free cancellation up to 2 hours before the scheduled visit.')),
                ('service_area', models.CharField(blank=True, default='Delhi-NCR', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
