# Generated by Django 6.1 on 2026-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used when pricing type is Per hour.', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='min_hours',
            field=models.PositiveIntegerField(default=1, help_text='Minimum billable hours for hourly services.'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed price'), ('hourly', 'Per hour')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='fixed_labour_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used when pricing type is Fixed price.', max_digits=10),
        ),
    ]
