# Generated by Django 6.1 on 2026-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours_booked',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
    ]
