# Generated by Django 6.1 on 2026-08-30 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_hours_booked'),
        ('catalog', '0002_service_hourly_rate_service_min_hours_and_more'),
        ('workers', '0003_alter_society_options_society_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers_required', models.PositiveIntegerField(default=1)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('claimed', 'Claimed by a society'), ('assigned', 'Workers assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=15)),
                ('visit_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('labour_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_requests', to='workers.society')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_requests', to='catalog.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_assignments', to='workers.workerprofile')),
                ('bulk_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings.bulkservicerequest')),
            ],
            options={
                'unique_together': {('bulk_request', 'worker')},
            },
        ),
    ]
