# Generated by Django 6.1 on 2026-09-01 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bulkservicerequest_bulkassignment'),
        ('catalog', '0002_service_hourly_rate_service_min_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('workers_required', models.PositiveIntegerField(default=1)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('hours_booked', models.DecimalField(decimal_places=1, default=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
            ],
        ),
    ]
