# Generated by Django 5.2.17 on 2026-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('waiting', 'Waiting for Acceptance'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('worker_arriving', 'Worker arriving'), ('arrived', 'Arrived'), ('work_started', 'Work started'), ('work_completed', 'Work completed'), ('customer_confirmed', 'Customer confirmed'), ('payment_settled', 'Payment settled'), ('rated', 'Rated'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected by worker')], default='requested', max_length=25),
        ),
    ]
