# Generated by Django 6.1 on 2026-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkservicerequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('awaiting_approval', 'Awaiting Approval'), ('claimed', 'Claimed by a society'), ('assigned', 'Workers assigned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='requested', max_length=25),
        ),
    ]
