# Generated by Django 6.1 on 2026-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bulkservicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkservicerequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('worker_arriving', 'Worker arriving'), ('arrived', 'Arrived'), ('work_started', 'Work started'), ('work_completed', 'Work completed'), ('customer_confirmed', 'Customer confirmed'), ('payment_settled', 'Payment settled'), ('rated', 'Rated'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='requested', max_length=25),
        ),
    ]
