# Generated by Django 6.1 on 2026-09-09 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bulkservicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='bulk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bookings.bulkservicerequest'),
        ),
        migrations.AlterField(
            model_name='bulkservicerequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('awaiting_approval', 'Awaiting approval'), ('claimed', 'Claimed by a society'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('work_started', 'Work started'), ('in_progress', 'In progress'), ('customer_confirmed', 'Customer confirmed'), ('payment_settled', 'Payment settled'), ('work_completed', 'Work completed'), ('rated', 'Rated'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bookings.booking'),
        ),
    ]
