# Generated by Django 6.1 on 2026-08-27 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('federation_name', models.CharField(default='Delhi-NCR Labour Federation', max_length=150)),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(blank=True, max_length=40)),
                ('membership_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('verified', 'Verified'), ('suspended', 'Temporarily suspended'), ('rejected', 'Rejected'), ('expired', 'Verification expired')], default='pending', max_length=20)),
                ('verification_officer', models.CharField(blank=True, max_length=150)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('skill_grade', models.CharField(choices=[('basic', 'Basic'), ('skilled', 'Skilled'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('certified', 'Certified professional')], default='basic', max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('languages_spoken', models.CharField(blank=True, default='Hindi, English', max_length=200)),
                ('service_radius_km', models.PositiveIntegerField(default=5)),
                ('is_available_now', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('payout_percentage', models.DecimalField(decimal_places=2, default=78.0, help_text='Percentage of total charge paid to the worker.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='workers', to='catalog.servicecategory')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.society')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('identity', 'Identity proof'), ('address', 'Address proof'), ('skill_cert', 'Skill certificate'), ('licence', 'Driving licence'), ('police', 'Police / background verification'), ('insurance', 'Insurance details'), ('training', 'Training certificate')], max_length=20)),
                ('file', models.FileField(upload_to='worker_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typical_arrival_minutes', models.PositiveIntegerField(default=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_offerings', to='catalog.service')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='workers.workerprofile')),
            ],
            options={
                'unique_together': {('worker', 'service')},
            },
        ),
    ]
