# Generated by Django 6.1 on 2026-08-30 20:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workercategorychangerequest_workerblockeddate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Societies'},
        ),
        migrations.AddField(
            model_name='society',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='society',
            name='operator',
            field=models.OneToOneField(blank=True, help_text="The user account (role=society) who verifies and manages this society's workers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_society', to=settings.AUTH_USER_MODEL),
        ),
    ]
