# Generated by Django 6.1 on 2026-09-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_society_options_society_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='federation_name',
        ),
        migrations.AddField(
            model_name='society',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='head_performs_fieldwork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='society',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False once deleted by Admin.'),
        ),
        migrations.AddField(
            model_name='society',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='society',
            name='resignation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='society',
            name='resigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_worked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='operator',
            field=models.OneToOneField(blank=True, help_text="The society's Head — the account who claims workers and manages the society's day-to-day operations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_society', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, help_text="Platform commission taken from this federation's earnings, set by Admin only.", max_digits=5)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False once deleted/deactivated by Admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.OneToOneField(blank=True, help_text='The user account (role=federation) who administers this federation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_federation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='society',
            name='federation',
            field=models.ForeignKey(blank=True, help_text='Null = independent society (sets its own pricing/policy). Set once a join request is accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='societies', to='workers.federation'),
        ),
        migrations.CreateModel(
            name='FederationJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(choices=[('society', 'Requested by the society'), ('federation', 'Invited by the federation')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='workers.federation')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_requests', to='workers.society')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FederationPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_overrides', models.JSONField(default=dict, help_text='Mapping of category_id to custom visit charge.')),
                ('service_overrides', models.JSONField(default=dict, help_text='Mapping of service_id to custom labour charge.')),
                ('federation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='workers.federation')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_overrides', models.JSONField(default=dict, help_text="Mapping of category_id to custom visit charge. e.g. {'1': 200, '2': 150}")),
                ('service_overrides', models.JSONField(default=dict, help_text="Mapping of service_id to custom labour charge. e.g. {'10': 500, '11': 300}")),
                ('society', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='workers.society')),
            ],
        ),
    ]
