# Generated by Django 5.2.17 on 2026-09-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_platformconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationpricing',
            name='category_overrides',
            field=models.JSONField(default=dict, help_text='Mapping of category_id to custom visit charge.'),
        ),
        migrations.AddField(
            model_name='federationpricing',
            name='federation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='workers.federation'),
        ),
        migrations.AddField(
            model_name='federationpricing',
            name='service_overrides',
            field=models.JSONField(default=dict, help_text='Mapping of service_id to custom labour charge.'),
        ),
    ]
