# Generated by Django 6.1 on 2026-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_federationpricing_category_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='address_proof',
            field=models.FileField(blank=True, help_text='Govt issued address proof', null=True, upload_to='worker_docs/address_proofs/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='certificate',
            field=models.FileField(blank=True, help_text='Professional certification or skill certificate', null=True, upload_to='worker_docs/certificates/'),
        ),
    ]
