# Generated by Django 5.2.17 on 2026-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_societyjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
