# Generated by Django 5.2.17 on 2026-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_societyjoinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='description',
            field=models.TextField(blank=True, help_text="Detailed description of the society's mission and services."),
        ),
    ]
