# Generated by Django 5.2.17 on 2026-09-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_federationpricing_category_overrides_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='workers.society')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_join_requests', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'society')},
            },
        ),
    ]
